### ISSUE TITLE
Getting duplicate messages when sending

### ISSUE THREAD

**Issue by mattheworiordan** [ably/demo-mobile-android#4]
Confirmed that I see duplicates in a Cordova app as well i.e. it's not just Anrdoid showing the message twice.

**Comment by stannedelchev** [comment]
Not able to reproduce this issue as well. I got duplicate messages when we were online together, but everything looks fine now, I've got the Android, iOS and Cordova apps opened.

**Comment by mattheworiordan** [comment]
Perhaps it's just a styling thing, it's light grey text on a light grey background.  Could you make the text slightly darker or ideally the same style as the cordova app with a lozenge?

**Comment by mattheworiordan** [comment]
Agreed, can't replicate
