### ISSUE TITLE
Typing indicator does not work

### ISSUE THREAD

**Issue by mattheworiordan** [ably/demo-mobile-android#5]

**Comment by stannedelchev** [comment]
@mattheworiordan Can you elaborate on this? I'm not able to reproduce the issue.
Typing in the Heroku app shows the typing indicator in Android and vice versa. 
After a few seconds both indicators hide. Am I missing something?

**Comment by mattheworiordan** [comment]
Perhaps it's just a styling thing, it's light grey text on a light grey background. Could you make the text slightly darker or ideally the same style as the cordova app with a lozenge?

**Comment by stannedelchev** [comment]
OK, fixed in 70f3d8952f205ac3e8d6390da510ebffd606856b.
